services:
  label-generator:
    container_name: label-generator
    build: .
    ports:
      - "4000:4000"
    restart: unless-stopped
    volumes:
      - /var/run/cups/cups.sock:/var/run/cups/cups.sock
    env_file:
      - .env
